### ISSUE TITLE
Remove .cpp, enum.d.ts, shims.d.ts

### ISSUE THREAD

**Issue by pelikhan** [CoderDojoOlney/pxt-olney#3]
You can safely remove those 3 files (+ remove ref from pxt.json) since they don't do anything. having C++ triggers a cloud compilation which could be avoided here.

**Comment by mmoskal** [comment]
+1

**Comment by Robotmad** [comment]
OK - they were left from experimenting and learning how to incorporate C++ code into Microbit packages.

**Comment by pelikhan** [comment]
Can you remove them?
