### ISSUE TITLE
Add icon.png

### ISSUE THREAD

**Issue by pelikhan** [CoderDojoOlney/pxt-olney#6]
We are working on displaying a small icons in the package search. It will be basically pull "icon.png" from master on this repo. Could you add a small image (16:9, 184px wide best) of your motor shield?

**Comment by microbit-mark** [comment]
@Robotmad Can you add the icon please?

**Comment by microbit-mark** [comment]
@Robotmad Polling this ticket again. Can you add an image please?

**Comment by Robotmad** [comment]
simple image of the shield used to implement the motors added
